GameData = Inherit([[]])
GameData["critical_bag"] = Reference([[bags\critical_bag.lua]])
GameData["critical_bag"]["actions"]["action_03"] = Reference([[action\critical_action\occupant_damage.lua]])
GameData["critical_bag"]["actions"]["action_03"]["ignore_invulnerability"] = true 
GameData["critical_bag"]["actions"]["action_03"]["ignore_team_weapon"] = true 
GameData["critical_bag"]["actions"]["action_03"]["max"] = 1
GameData["critical_bag"]["actions"]["action_03"]["subactions"]["action_01"] = Reference([[action\critical_action\make_dead.lua]])
GameData["critical_bag"]["actions"]["action_03"]["subactions"]["action_01"]["death_intensity"] = [[death_intensity_ragdoll]]
GameData["critical_bag"]["actions"]["action_03"]["subactions"]["action_02"] = Reference([[action\critical_action\game_event_action.lua]])
GameData["critical_bag"]["actions"]["action_03"]["subactions"]["action_02"]["event_param_begin"] = 0
GameData["critical_bag"]["actions"]["action_03"]["subactions"]["action_02"]["event_type"] = [[sniped]]
GameData["critical_bag"]["description"] = [[Soldier Sniped]]
GameData["critical_bag"]["kicker_message"]["message_colour_r"] = 255
