GameData = Inherit([[]])
GameData["critical_bag"] = Reference([[bags\critical_bag.lua]])
GameData["critical_bag"]["actions"]["action_01"] = Reference([[action\critical_action\apply_modifiers_action.lua]])
GameData["critical_bag"]["actions"]["action_01"]["duration"] = 10
GameData["critical_bag"]["actions"]["action_01"]["modifiers"]["modifier_01"] = Reference([[modifiers\shoot_enable_modifier.lua]])
GameData["critical_bag"]["actions"]["action_01"]["modifiers"]["modifier_01"]["value"] = -1
GameData["critical_bag"]["description"] = [[Stunned, Can't Shoot]]
GameData["critical_bag"]["kicker_message"]["message"] = "$138850"
GameData["critical_bag"]["kicker_message"]["message_colour_r"] = 255
GameData["critical_bag"]["kicker_message"]["message_seconds"] = 5
