GameData = Inherit([[]])
GameData["critical_bag"] = Reference([[bags\critical_bag.lua]])
GameData["critical_bag"]["actions"]["action_06"] = Reference([[action\critical_action\requirement_action.lua]])
GameData["critical_bag"]["actions"]["action_06"]["action_table"]["ability_actions"]["action_01"] = Reference([[action\ability_action\stop_ability_action.lua]])
GameData["critical_bag"]["actions"]["action_06"]["action_table"]["ability_actions"]["action_01"]["ability_to_stop"] = [[abilities\pe_overdrive.lua]]
GameData["critical_bag"]["critical_indicators"]["indicator_01"] = [[vehicle_engine_yellow]]
GameData["critical_bag"]["description"] = [[yellow damage engine]]
GameData["critical_bag"]["kicker_message"]["message"] = "$143850"
GameData["critical_bag"]["kicker_message"]["message_colour_r"] = 255
GameData["critical_bag"]["kicker_message"]["message_seconds"] = 10
