GameData = Inherit([[]])
GameData["combat_slot_00"] = Reference([[tables\hold_combot_slot_info.lua]])
GameData["combat_slot_00"]["use_slot_heading"] = true 
GameData["combat_slot_01"] = Reference([[tables\hold_combot_slot_info.lua]])
GameData["combat_slot_01"]["use_slot_heading"] = true 
GameData["combat_slot_02"] = Reference([[tables\hold_combot_slot_info.lua]])
GameData["combat_slot_02"]["use_slot_heading"] = true 
GameData["combat_slot_03"] = Reference([[tables\hold_combot_slot_info.lua]])
GameData["combat_slot_03"]["use_slot_heading"] = true 
GameData["combat_slot_04"] = Reference([[tables\hold_combot_slot_info.lua]])
GameData["combat_slot_04"]["type"] = [[infantry only]]
GameData["combat_slot_04"]["use_slot_heading"] = true 
GameData["combat_slot_05"] = Reference([[tables\hold_combot_slot_info.lua]])
GameData["combat_slot_06"] = Reference([[tables\hold_combot_slot_info.lua]])
