GameData = Inherit([[]])
GameData["modifier_01"] = Reference([[tables\time_modify_entry.lua]])
GameData["modifier_02"] = Reference([[tables\time_modify_entry.lua]])
GameData["modifier_03"] = Reference([[tables\time_modify_entry.lua]])
GameData["modifier_04"] = Reference([[tables\time_modify_entry.lua]])
GameData["modifier_05"] = Reference([[tables\time_modify_entry.lua]])
