GameData = Inherit([[]])
GameData["critical_list"] = Reference([[tables\critical_list_table.lua]])
GameData["critical_list"]["critical_01"] = [[critical\vehicle_halftrack_sdkfz_251_kill_mg42_gunner_rear.lua]]
GameData["critical_list"]["critical_02"] = [[critical\vehicle_halftrack_sdkfz_251_kill_mg42_gunner_front.lua]]
GameData["critical_list"]["critical_03"] = [[critical\vehicle_halftrack_m3_kill_50cal_gunner.lua]]
GameData["critical_list"]["critical_04"] = [[critical\vehicle_kill_top_gunner_allied.lua]]
GameData["critical_list"]["critical_05"] = [[critical\vehicle_kill_top_gunner_allied_greyhound.lua]]
GameData["critical_list"]["critical_06"] = [[critical\vehicle_kill_top_gunner_axis_tank.lua]]
GameData["critical_list"]["critical_07"] = [[critical\vehicle_kill_top_gunner_axis_stug.lua]]
GameData["critical_list"]["critical_08"] = [[critical\vehicle_destroy_hetzer_gun.lua]]
GameData["critical_list"]["critical_09"] = [[critical\villers_bocage_kill_commander.lua]]
GameData["description"] = [[Destroy vehicle secondary weapon]]
