GameData = Inherit([[]])
GameData["slot_item_bag"] = Reference([[bags\slot_item_bag.lua]])
GameData["slot_item_bag"]["can_drop"] = false
GameData["slot_item_bag"]["hardpoint"] = 4
GameData["slot_item_bag"]["has_speech_code"] = true 
GameData["slot_item_bag"]["slot_size"] = 1
GameData["slot_item_bag"]["speech_code_2"]["code_1"] = [[50]]
GameData["slot_item_bag"]["speech_code_3"]["code_1"] = [[50C]]
GameData["slot_item_bag"]["ui_info"]["hotkey_name"] = [[allies_sherman_machinegun_mount	]]
GameData["slot_item_bag"]["ui_unit_ratings"]["vs_infantry"] = 3
GameData["slot_item_bag"]["weapon"]["origin"]["y"] = 3
GameData["slot_item_bag"]["weapon"]["type"] = [[squad]]
GameData["slot_item_bag"]["weapon"]["weapon"] = [[weapon\allies\small_arms\machine_gun\heavy_machine_gun\m2hb_turret_mount_staghound.lua]]
