GameData = Inherit([[]])
GameData["type_target_assault"] = Reference([[type_target_assault\tp_deftarget.lua]])
GameData["type_target_critical"] = Reference([[type_target_critical\tp_deftarget.lua]])
GameData["type_target_weapon"] = Reference([[type_target_weapon\tp_deftarget.lua]])
GameData["unit_type_list"] = Reference([[tables\unit_type_list.lua]])
